{"name": "test_login_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1", "trace": "self = <test_allure.TestLogin object at 0x0000017B77CE3790>\n\n    @allure.story(\"密码缺失\")\n    def test_login_failure(self):\n        with allure.step(\"点击用户名\"):\n            print(\"输入用户名\")\n        with allure.step(\"点击密码\"):\n            print(\"输入密码\")\n        print(\"点击登录\")\n        with allure.step(\"点击登录之后失败\"):\n>           assert  '1' == 1\nE           AssertionError: assert '1' == 1\n\ntest_allure.py:30: AssertionError"}, "steps": [{"name": "点击用户名", "status": "passed", "start": 1631086687710, "stop": 1631086687710}, {"name": "点击密码", "status": "passed", "start": 1631086687710, "stop": 1631086687710}, {"name": "点击登录之后失败", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1\n", "trace": "  File \"E:\\python\\hogwarts_test\\test_allure.py\", line 30, in test_login_failure\n    assert  '1' == 1\n"}, "start": 1631086687710, "stop": 1631086687710}], "attachments": [{"name": "stdout", "source": "d3267d05-fcea-4589-9258-3639e42a800f-attachment.txt", "type": "text/plain"}], "start": 1631086687710, "stop": 1631086687710, "uuid": "a02e40c5-5648-4e3a-a862-9e727434a21c", "historyId": "ec96e39999f53a6ff844a9debe8d6116", "testCaseId": "52ba3826c163dc76f5affd16329fca3b", "fullName": "test_allure.TestLogin#test_login_failure", "labels": [{"name": "story", "value": "密码缺失"}, {"name": "feature", "value": "登录模块"}, {"name": "suite", "value": "test_allure"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "only"}, {"name": "thread", "value": "692-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_allure"}]}